import {test} from 'node:test';import assert from 'node:assert/strict';
import {stable,validateAction,validateResult,validClaims} from './core.mjs';
const ID='00000000-0000-4000-8000-000000000000';
const evidence=()=>({mode:'deterministic',summary:'Executed evaluation',artifacts:[{name:'report.md',content:'# Proof'}],sources:[],usage:{status:'not_billed_here',input_tokens:0,output_tokens:0}});
const claims=()=>({iss:'https://token.actions.githubusercontent.com',aud:'astra-company',repository:'mikelninh/Agent-Proof',repository_id:'1371282495',ref:'refs/heads/astra/company-operations',workflow_ref:'mikelninh/Agent-Proof/.github/workflows/astra-company.yml@refs/heads/astra/company-operations',event_name:'push',iat:1000,exp:1600});
test('canonical evidence hashing ignores object key order',()=>assert.equal(stable({z:2,a:1}),stable({a:1,z:2})));
test('canonical evidence distinguishes booleans and integers',()=>assert.notEqual(stable(true),stable(1)));
test('founder creates a bounded job',()=>validateAction('create',{title:'Pilot',kind:'service_pack',brief:'No sends',request_key:'request-one',priority:50},'founder'));
for(const action of ['decide','create','retry','pause','snapshot'])test('worker denied '+action,()=>assert.throws(()=>validateAction(action,{},'worker')));
test('founder cannot impersonate executor',()=>assert.throws(()=>validateAction('finish',{},'founder')));
test('version required for decision',()=>assert.throws(()=>validateAction('decide',{id:ID,decision:'approve'},'founder')));
test('valid evidence accepted for human review only',()=>validateResult(evidence()));
test('path traversal rejected',()=>{let e=evidence();e.artifacts[0].name='../x.md';assert.throws(()=>validateResult(e));});
test('empty fake output rejected',()=>{let e=evidence();e.artifacts[0].content='';assert.throws(()=>validateResult(e));});
test('unknown costs not converted to zero',()=>{let e=evidence();e.usage={status:'unknown',input_tokens:null,output_tokens:null};validateResult(e);});
test('negative tokens rejected',()=>{let e=evidence();e.usage.input_tokens=-1;assert.throws(()=>validateResult(e));});
test('duplicate artifact rejected',()=>{let e=evidence();e.artifacts.push(e.artifacts[0]);assert.throws(()=>validateResult(e));});
test('model-backed work requires provenance',()=>{let e=evidence();e.mode='model_backed';assert.throws(()=>validateResult(e));});
test('valid GitHub identity contract',()=>assert.equal(validClaims(claims(),1100),true));
for(const [k,v] of Object.entries({iss:'https://attacker.test',aud:'wrong',repository:'other/repo',repository_id:'1',ref:'refs/heads/main',workflow_ref:'wrong.yml',event_name:'pull_request',exp:900,iat:1500}))test('OIDC rejects wrong '+k,()=>assert.equal(validClaims({...claims(),[k]:v},1100),false));
test('expired OIDC rejects',()=>assert.equal(validClaims(claims(),1601),false));
test('unsupported task kind denied',()=>assert.throws(()=>validateAction('create',{title:'Execute shell',kind:'shell',brief:'',priority:1,request_key:'123456789'},'founder')));
test('pause is a real boolean',()=>assert.throws(()=>validateAction('pause',{paused:'false'},'founder')));