const $ = id => document.getElementById(id);
const esc = s => String(s ?? '').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]));
const pct = x => `${(x*100).toFixed(1)}%`;
const eur = x => new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(x||0);
const eur4 = x => new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:4}).format(x||0);
let currentRun=null,currentComparison=null,csvState=null,advState=[];

async function api(url, options={}){
  const r=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});
  if(!r.ok) throw new Error((await r.text())||`HTTP ${r.status}`);
  return r.json();
}

async function loadPacks(selectId){
  const packs=await api('/api/packs');
  $('packSelect').innerHTML=packs.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${p.case_count} cases</option>`).join('');
  if(selectId) $('packSelect').value=selectId;
}
function providerUI(){document.querySelectorAll('.remote').forEach(x=>x.style.display='none'); if($('provider').value==='openai_compatible')document.querySelectorAll('.only-openai').forEach(x=>x.style.display='block'); if($('provider').value==='webhook')document.querySelectorAll('.only-webhook').forEach(x=>x.style.display='block');}
$('provider').onchange=providerUI;

function requestPayload(){
  const p=$('provider').value;
  const names={demo_baseline:'Demo baseline',demo_candidate:'Demo candidate v2',demo_risky:'Demo aggressive v3'};
  return {pack_id:$('packSelect').value,agent:{provider:p,name:names[p]||$('model').value||'Custom agent',model:$('model').value||null,base_url:$('baseUrl').value||null,api_key:$('apiKey').value||null,webhook_url:$('webhookUrl').value||null,input_cost_per_million_eur:+$('inputCost').value||0,output_cost_per_million_eur:+$('outputCost').value||0},economics:{human_minutes_per_case:+$('humanMinutes').value,human_hourly_cost_eur:+$('humanHourly').value,annual_case_volume:+$('annualVolume').value,implementation_cost_eur:+$('implementationCost').value},gate:{min_success_rate:+$('minSuccess').value/100,max_critical_failure_rate:+$('maxCritical').value/100,max_agent_cost_per_case_eur:null,max_annual_failure_exposure_eur:null}};
}
async function runEval(){
  $('runState').classList.remove('hidden');
  try{currentRun=await api('/api/runs',{method:'POST',body:JSON.stringify(requestPayload())}); await renderRun(currentRun); await loadHistory();}
  catch(e){alert(`Evaluation failed: ${e.message}`)} finally{$('runState').classList.add('hidden')}
}
function metric(k,v,s='',cls=''){return `<div class="metric ${cls}"><div class="k">${k}</div><div class="v">${v}</div><div class="s">${s}</div></div>`}
async function renderRun(run){
  currentRun=run; const m=run.metrics;
  $('runTitle').textContent=`${run.pack_name} · ${run.agent.name}`;
  $('metrics').innerHTML=[metric('Deployment gate',run.gate.status==='pass'?'PASS':'BLOCK',run.gate.reasons[0]||'all thresholds satisfied',run.gate.status==='pass'?'good':'danger'),metric('Success',pct(m.success_rate),`${m.total_cases} cases`,m.success_rate>=.95?'good':''),metric('Critical',pct(m.critical_failure_rate),'dangerous policy failures',m.critical_failure_rate?'danger':'good'),metric('Failure exposure',eur(m.annualized_failure_exposure_eur),'annualized from observed misses',m.annualized_failure_exposure_eur?'danger':''),metric('Risk-adjusted value',eur(m.risk_adjusted_annual_value_eur),'annual labour value − failure exposure',m.risk_adjusted_annual_value_eur>0?'good':''),metric('Cost / case',eur4(m.agent_cost_per_case_eur),`human ${eur4(m.human_cost_per_case_eur)}`)].join('');
  const failed=run.cases.filter(c=>!c.grade.passed),critical=run.cases.filter(c=>c.grade.critical_failure);
  $('summaryStrip').innerHTML=`<span><b>${failed.length}</b> mismatches</span><span><b>${critical.length}</b> critical</span><span><b>${pct(m.escalation_rate)}</b> escalated</span><span><b>${m.avg_latency_ms.toFixed(1)}ms</b> avg latency</span>`;
  const rows=[...run.cases].sort((a,b)=>(+b.grade.critical_failure-+a.grade.critical_failure)||(+a.grade.passed-+b.grade.passed)||b.failure_cost_eur-a.failure_cost_eur);
  $('caseRows').innerHTML=rows.map((c,i)=>{const field=Object.keys(c.expected)[0],expected=c.expected[field],actual=c.output.parsed[field]??'error'; const risk=c.grade.critical_failure?'<span class="pill critical">critical</span>':c.grade.passed?'<span class="pill ok">pass</span>':'<span class="pill review">mismatch</span>'; return `<tr data-i="${i}"><td>${esc(c.title)}</td><td>${esc(expected)}</td><td>${esc(actual)}</td><td>${(c.grade.score*100).toFixed(0)}</td><td>${risk}</td></tr>`}).join('');
  document.querySelectorAll('#caseRows tr').forEach(tr=>tr.onclick=()=>renderTrace(rows[+tr.dataset.i]));
  const coverage=await api(`/api/runs/${run.id}/coverage`); renderCoverage(coverage);
  $('results').classList.remove('hidden'); $('results').scrollIntoView({behavior:'smooth',block:'start'});
}
function renderTrace(c){$('traceEmpty').classList.add('hidden');$('trace').classList.remove('hidden');$('trace').innerHTML=`<div class="trace-block"><h4>Agent-visible input</h4><pre>${esc(JSON.stringify(c.input,null,2))}</pre></div><div class="trace-block"><h4>Agent output</h4><pre>${esc(c.output.raw_text||c.output.error||'No output')}</pre></div><div class="trace-block"><h4>Hidden ground truth</h4><pre>${esc(JSON.stringify(c.expected,null,2))}</pre></div><div class="trace-block"><h4>Grader evidence</h4>${c.grade.reasons.length?c.grade.reasons.map(r=>`<div class="reason">${esc(r)}</div>`).join(''):'<span class="pill ok">all fields matched</span>'}</div><div class="trace-block"><h4>Potential miss cost</h4><pre>${eur(c.failure_cost_eur)}</pre></div>`}
function renderCoverage(items){$('coverage').innerHTML=items.slice(0,16).map(x=>`<div class="coverage-card ${x.success_rate<.95?'weak':''}"><div><strong>${esc(x.tag)}</strong><span>${x.cases} cases</span></div><div class="coverage-rate">${pct(x.success_rate)}</div><div class="bar"><i style="width:${x.success_rate*100}%"></i></div><small>${x.critical_failures} critical · ${eur(x.failure_exposure_eur)} observed exposure</small></div>`).join('')}

async function loadHistory(){
  const runs=await api('/api/runs');
  $('history').innerHTML=runs.length?runs.map(r=>`<div class="history-card" data-id="${r.id}"><div><strong>${esc(r.pack_name)}</strong><span>${esc(r.agent_name)}</span></div><div><span>Gate</span><b class="${r.gate.status==='pass'?'green':'red'}">${r.gate.status.toUpperCase()}</b></div><div><span>Success</span><b>${pct(r.metrics.success_rate)}</b></div><div><span>Risk value</span><b>${eur(r.metrics.risk_adjusted_annual_value_eur)}</b></div></div>`).join(''):'<div class="empty">No runs yet.</div>';
  document.querySelectorAll('.history-card').forEach(el=>el.onclick=async()=>renderRun(await api(`/api/runs/${el.dataset.id}`)));
  const options=runs.map(r=>`<option value="${r.id}">${esc(r.pack_name)} · ${esc(r.agent_name)} · ${pct(r.metrics.success_rate)}</option>`).join(''); $('baselineRun').innerHTML=options;$('candidateRun').innerHTML=options;
  if(runs.length>=2){$('candidateRun').value=runs[0].id; const same=runs.slice(1).find(r=>r.pack_id===runs[0].pack_id); $('baselineRun').value=(same||runs[1]).id;}
}
async function compareRuns(){const b=$('baselineRun').value,c=$('candidateRun').value;if(!b||!c||b===c)return alert('Choose two different runs from the same pack.');try{currentComparison=await api('/api/compare',{method:'POST',body:JSON.stringify({baseline_run_id:b,candidate_run_id:c})});renderComparison(currentComparison)}catch(e){alert(e.message)}}
function renderComparison(c){$('compareEmpty').classList.add('hidden');$('compareResult').classList.remove('hidden');$('exportComparison').classList.remove('hidden');$('comparisonBanner').className=`comparison-banner ${c.recommendation}`;$('comparisonBanner').textContent=`${c.recommendation.toUpperCase()} · ${c.candidate_agent}`;$('compareMetrics').innerHTML=[metric('Success',`${pct(c.baseline_success_rate)} → ${pct(c.candidate_success_rate)}`,`${c.success_rate_delta>=0?'+':''}${pct(c.success_rate_delta)}`),metric('Fixes',c.fixes,`${c.regressions} regressions`,c.fixes>c.regressions?'good':'danger'),metric('New critical',c.new_critical_failures,`${c.resolved_critical_failures} resolved`,c.new_critical_failures?'danger':'good'),metric('Paired p',c.mcnemar_p_value.toFixed(4),`${c.discordant_pairs} changed pairs`)].join('');$('comparisonReasons').innerHTML=c.reasons.map(r=>`<span class="reason-chip">${esc(r)}</span>`).join('');const changed=c.cases.filter(x=>x.status!=='unchanged');$('comparisonRows').innerHTML=changed.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.baseline_decision)}</td><td>${esc(x.candidate_decision)}</td><td><span class="pill ${x.status==='fix'?'ok':'critical'}">${x.status}</span>${x.candidate_critical&&!x.baseline_critical?' <span class="pill critical">new critical</span>':''}</td></tr>`).join('')||'<tr><td colspan="4">No changed cases.</td></tr>'}

async function runCaseStudy(){
  $('runState').classList.remove('hidden');
  try{const s=await api('/api/case-study/support',{method:'POST'});$('caseStudy').classList.remove('hidden');$('studySummary').innerHTML=s.executive_summary.map(x=>`<span>${esc(x)}</span>`).join('');const entries=[['Baseline',s.baseline],['Candidate v2',s.candidate],['Aggressive v3',s.risky]];$('studyGrid').innerHTML=entries.map(([label,r])=>`<article class="study-card ${r.gate.status}"><div class="study-label">${label}</div><h3>${esc(r.agent.name)}</h3><div class="study-number">${pct(r.metrics.success_rate)}</div><div class="study-meta"><span>${r.gate.status.toUpperCase()} gate</span><span>${pct(r.metrics.critical_failure_rate)} critical</span><span>${eur(r.metrics.annualized_failure_exposure_eur)} risk/yr</span></div></article>`).join('');$('studyDecision').innerHTML=`<div><div class="eyebrow">Release decision</div><h3>${s.candidate_comparison.recommendation.toUpperCase()} candidate v2 · ${s.risky_comparison.recommendation.toUpperCase()} aggressive v3</h3><p>${esc(s.candidate_comparison.reasons.join(' · '))}</p></div>`; $('caseStudyReport').onclick=()=>window.open(`/api/runs/${s.candidate.id}/report.md`,'_blank'); await loadHistory(); $('caseStudy').scrollIntoView({behavior:'smooth'});}catch(e){alert(e.message)}finally{$('runState').classList.add('hidden')}
}

async function generateAdversarial(){try{const result=await api(`/api/packs/${encodeURIComponent($('packSelect').value)}/adversarial-drafts`,{method:'POST',body:JSON.stringify({limit:+$('advLimit').value,families:['missing','boundary','boolean_flip','conflict','scale']})});advState=result.drafts;$('advWarning').textContent=result.warning;$('advWarning').classList.remove('hidden');$('approveAdv').classList.remove('hidden');$('advDrafts').innerHTML=advState.map((d,i)=>`<article class="adv-card"><label class="approve-check"><input type="checkbox" data-approve="${i}"/> confirm ground truth</label><div class="pill neutral">${esc(d.family)}</div><h4>${esc(d.title)}</h4><p>${esc(d.rationale)}</p><details><summary>Mutated input</summary><pre>${esc(JSON.stringify(d.input,null,2))}</pre></details><label>Confirmed expected JSON<textarea data-expected="${i}">${esc(JSON.stringify(d.suggested_expected))}</textarea></label></article>`).join('')}catch(e){alert(e.message)}}
async function approveAdversarial(){const selected=[...document.querySelectorAll('[data-approve]:checked')];if(!selected.length)return alert('Confirm at least one draft first.');const cases=[];try{for(const cb of selected){const i=+cb.dataset.approve;cases.push({draft:advState[i],expected:JSON.parse(document.querySelector(`[data-expected="${i}"]`).value)})}const base=$('packSelect').value,id=`${base}-adversarial-${Date.now().toString().slice(-6)}`;await api(`/api/packs/${encodeURIComponent(base)}/adversarial-approve`,{method:'POST',body:JSON.stringify({id,name:`${base} · approved adversarial`,description:'Human-approved adversarial cases',cases})});await loadPacks(id);alert(`Created ${cases.length}-case approved adversarial pack. It is now selected.`)}catch(e){alert(`Could not create pack: ${e.message}`)}}

// Historical CSV pilot mode
const pii=/(full.?name|first.?name|last.?name|email|phone|mobile|address|street|postcode|postal|zip|birth|dob|ssn|iban|bank.?account|card.?number|passport|national.?id|ip.?address|device.?id)/i;
function parseCsv(text){const rows=[];let row=[],field='',q=false;text=text.replace(/^\uFEFF/,'');for(let i=0;i<text.length;i++){const ch=text[i];if(q){if(ch==='\"'&&text[i+1]==='\"'){field+='\"';i++}else if(ch==='\"')q=false;else field+=ch}else{if(ch==='\"')q=true;else if(ch===','){row.push(field);field=''}else if(ch==='\n'){row.push(field.replace(/\r$/,''));rows.push(row);row=[];field=''}else field+=ch}}if(field||row.length){row.push(field);rows.push(row)}const non=rows.filter(r=>r.some(v=>String(v).trim()));if(non.length<2)throw new Error('CSV needs a header and at least one row.');const headers=non[0].map(x=>x.trim());if(new Set(headers).size!==headers.length)throw new Error('Duplicate column names.');const malformed=non.slice(1).filter(r=>r.length!==headers.length).length;return {headers,data:non.slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,(r[i]??'').trim()]))),malformed}}
const slug=s=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60);
function openCsv(state){csvState=state;const name=state.fileName.replace(/\.csv$/i,'').replace(/[_-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());$('csvPackName').value=name||'Historical Evaluation';$('csvPackId').value=slug(name||'historical-evaluation')+'-v1';$('csvInstruction').value='Review this case and return one JSON object containing the correct decision.';const opts=state.headers.map(h=>`<option value="${esc(h)}">${esc(h)}</option>`).join('');$('csvTarget').innerHTML=opts;$('csvTitleColumn').innerHTML='<option value="">Auto-number</option>'+opts;const target=state.headers.find(h=>/(decision|outcome|label|status|resolution|target|result)/i.test(h));if(target)$('csvTarget').value=target;renderCsv();$('csvModal').classList.remove('hidden');document.body.classList.add('modal-open')}
function closeCsv(){$('csvModal').classList.add('hidden');document.body.classList.remove('modal-open')}
function renderCsv(){const target=$('csvTarget').value;$('csvColumns').innerHTML=csvState.headers.filter(h=>h!==target).map(h=>`<label class="column-choice ${pii.test(h)?'pii':''}"><input type="checkbox" value="${esc(h)}" checked/><span>${esc(h)}</span>${pii.test(h)?'<b>possible PII</b>':''}</label>`).join('');const vals=csvState.data.map(r=>r[target]),missing=vals.filter(v=>!v).length,dist={};vals.filter(Boolean).forEach(v=>dist[v]=(dist[v]||0)+1);$('csvStats').innerHTML=`<span><b>${csvState.data.length}</b> rows</span><span><b>${missing}</b> missing targets</span><span><b>${csvState.malformed}</b> malformed</span><span><b>${Object.keys(dist).length}</b> labels</span>`;renderCsvPreview()}
function visibleCols(){return [...document.querySelectorAll('#csvColumns input:checked')].map(x=>x.value)}
function renderCsvPreview(){const cols=visibleCols(),target=$('csvTarget').value;$('csvPreviewHead').innerHTML=`<tr>${cols.slice(0,4).map(c=>`<th>${esc(c)}</th>`).join('')}<th class="hidden-truth">hidden: ${esc(target)}</th></tr>`;$('csvPreviewBody').innerHTML=csvState.data.slice(0,5).map(r=>`<tr>${cols.slice(0,4).map(c=>`<td>${esc(r[c])}</td>`).join('')}<td class="hidden-truth">${esc(r[target])}</td></tr>`).join('')}
async function createCsvPack(){const target=$('csvTarget').value,cols=visibleCols();if(!cols.length)return alert('Select at least one visible input column.');const rules=[];if($('csvCriticalExpected').value&&$('csvCriticalActual').value)rules.push({field:target,expected:$('csvCriticalExpected').value,actual:$('csvCriticalActual').value});const titleCol=$('csvTitleColumn').value,cases=csvState.data.filter(r=>r[target]).map((r,i)=>({id:`${$('csvPackId').value}-${String(i+1).padStart(4,'0')}`,title:titleCol&&r[titleCol]?r[titleCol]:`Case ${i+1}`,input:Object.fromEntries(cols.map(c=>[c,r[c]])),expected:{[target]:r[target]},tags:['imported'],failure_cost_eur:0}));const pack={id:$('csvPackId').value,name:$('csvPackName').value,description:`Imported from ${csvState.fileName}`,task_instruction:$('csvInstruction').value,grader:{type:'json_fields',required_fields:[target],field_weights:{[target]:1},critical_mismatches:rules},cases};await api('/api/packs',{method:'POST',body:JSON.stringify(pack)});closeCsv();await loadPacks(pack.id);alert(`Created ${cases.length}-case evaluation pack.`)}

$('caseStudyBtn').onclick=runCaseStudy;$('runSelected').onclick=runEval;$('compareRuns').onclick=compareRuns;$('generateAdv').onclick=generateAdversarial;$('approveAdv').onclick=approveAdversarial;$('exportReport').onclick=()=>currentRun&&window.open(`/api/runs/${currentRun.id}/report.md`,'_blank');$('exportComparison').onclick=()=>currentComparison&&window.open(`/api/compare/${currentComparison.baseline_run_id}/${currentComparison.candidate_run_id}/report.md`,'_blank');
$('uploadBtn').onclick=()=>$('packFile').click();$('packFile').onchange=async e=>{try{const pack=JSON.parse(await e.target.files[0].text());await api('/api/packs',{method:'POST',body:JSON.stringify(pack)});await loadPacks(pack.id)}catch(err){alert(err.message)}e.target.value=''};
$('importCsvBtn').onclick=()=>$('csvFile').click();$('csvFile').onchange=async e=>{try{const f=e.target.files[0],parsed=parseCsv(await f.text());openCsv({...parsed,fileName:f.name})}catch(err){alert(err.message)}e.target.value=''};
$('csvTarget').onchange=renderCsv;$('csvColumns').onchange=renderCsvPreview;$('selectSafeColumns').onclick=()=>{document.querySelectorAll('#csvColumns .pii input').forEach(x=>x.checked=false);renderCsvPreview()};$('csvClose').onclick=closeCsv;$('csvCancel').onclick=closeCsv;$('csvCreate').onclick=()=>createCsvPack().catch(e=>alert(e.message));

providerUI(); loadPacks('support-ops-v1'); loadHistory();
